### ISSUE TITLE
Service Status Details For All Hosts doesn't count filtered match

### ISSUE THREAD

**Issue by EstebanMonge** [NagiosEnterprises/nagiosvshell#10]
Hello folks:

I again testing V-Shell 2.0.

When you display Service Status Details For All Hosts and filter events, the filtered match doesn't match with result count.

I make two screenshot to explain me better:
https://i.imgur.com/spRImQ4.png
The filter only match with 26 results

But counter still with the total without filter:
http://i.imgur.com/HKzMb9x.png
Still counting 403 results

**Comment by chrislaskey** [comment]
Hey Esteban,

Thanks for another insightful data point. Appreciate it!

The filtering is handled by the table sorting plugin, while the table count is updated by AngularJS. There may be a way to hook into the plugin and update the AngularJS count on filtering. I will have to take a look into the code and see what I come up with.

This is a low priority fix, so I can't promise a quick fix.

Best,

Chris

**Comment by hedenface** [comment]
Heh. Obviously *really* wasn't a quick fix, and most *definitely* was low priority. amiright?
Seriously though - I'm going to close this for the simple reason that there hasn't been activity in 2 years. We will definitely revisit this when we get to vshell (soon I hope!).

Otherwise, if this is something you **really** want to see happen soon - re-open it and I'll work some magic.
