### ISSUE TITLE
Create Let the webinterface show 'alias' instead of 'host_name'.

### ISSUE THREAD

**Issue by chrislaskey** [NagiosEnterprises/nagiosvshell#12]
As stated in the title, why not let the webinterface show the 'alias' name instead of the 'host_name'? 
This way, you only have to write down the long name once instead of several times, depending on the amount of services. I tried
messing with the PHP code but my PHP knowledge isn't good enough.

I posted this question in the vshell support forum and I got redirected here.

I hope I provided enough information, if not I'm sure you can contact me somehow.

Thanks for your time,

-Tycser

**Comment by chrislaskey** [comment]
**Note:** I created this GitHub Issue and closed the original PR request by @tycser (https://github.com/NagiosEnterprises/nagiosvshell/pull/11) request, since it did not contain actual code changes.

**Comment by chrislaskey** [comment]
Okay so to respond to your actual request, that sounds interesting.

Would you mind posting a screen shot or two calling out the area you'd like to see improved? I want to make sure changes are clear to all users, so they have a chance to chime in on discussion. That would be a huge help!

**Comment by tycser** [comment]
Can do, I am currently at home but I'll get some screen's tomorrow. Thanks for taking this kinda seriously! I'll comment her once I got the screenshots.

**Comment by tycser** [comment]
So here is an example: 

![definehostaliasexample](https://cloud.githubusercontent.com/assets/3873396/7085783/7ef1e9ba-df7a-11e4-9841-3c53ccb147b2.PNG)

Instead of placing the 'host_name', which you have to specify with every service you define, the 'alias' gets placed under 'Host Name' on the web interface. This should work for every page with a 'Host Name' column. See image below.

So taking the example above, the first row under the column 'Host Name' should say the 'alias'(My Server With A Long Server Name) instead of 'host_name'(server1). 

![alias example](https://cloud.githubusercontent.com/assets/3873396/7085690/770d23d2-df79-11e4-9f40-869ef8c3eafb.png)

This addition would help a lot with hosts with more then a few services as you have to write the 'host_name' every single time, and gives a (better) use for the 'alias' variable. 

I hope I explained it enough, not sure how I can do it any better. Lemme know what ya think! 

-Tycser

(Again, I'm new to all this stuff so forgive me if I did anything wrong.)

**Comment by mguthrie88** [comment]
I think this is something that could exist as a config option. This as well as host notes is something that has come up before. I think the best overall solution would be to have all display columns configurable, and just have a default in place like it is now. Some environments go entirely by alias, others, like ours, the only thing that really matters is host name.

**Comment by tycser** [comment]
I'll let the dev's decide on what they want to do with this information, I just found it curious that it didn't use the 'alias'. Can you guys take it from here or do I need to post this somewhere else?

**Comment by hedenface** [comment]
This seems reasonable... but.. @tycser since you're ONLY activity on github was due to your contribution to this project, and you haven't been active since 2015, I'm going to close this issue. If you decide that is in error, please let me know and we'll take a gander. Otherwise, we'll get to it when we get around to vshell in general. Thanks!
