### ISSUE TITLE
IP in Host Details 

### ISSUE THREAD

**Issue by EstebanMonge** [NagiosEnterprises/nagiosvshell#8]
Hello again... I am testing VShell... but I want know if are planning to put the IP in host details?

I think that is usefull... It can reduce my visits to old nagios CGIs.

If I can I will to try to put myself and If I can I wll send the code.
Thanks!!!

**Comment by EstebanMonge** [comment]
Hello. I saw that vshell parse status.dat for get information.
In status.dat the IP address doesnt appears.

I want to know how can I get the ip address?

**Comment by mguthrie88** [comment]
This is in the objects.cache file as the hostaddress field.

**Comment by jahunter** [comment]
The config_viewer.php file displays all the host attributes, including the IP address.  However, I'm having no end of a job trying to extract just the IP address for a given host.
I can see that I need to build a function similar to build_object_list($data, $arg).  The $arg I have no problem with but I can't find the source for the $data element.  Can you help with this please?

I tacked the $data back to the function object_output() but then the trail went cold as I could find any reference to that function anywhere!

**Comment by jahunter** [comment]
It's OK.  I got it.

I edited the hostdetails.php page that can be found in the 'view' folder, as follows:

Add the following function to the foot of the file just before the close php tag.

```
function get_host_ip($hostname){
	global $NagiosData;
	$data = $NagiosData->getProperty('hosts_objs');
	$ip = "Not found";
	foreach($data as $a){
		$name=$a['host_name'];
		if($name == $hostname){
			$ip = $a['address'];
			break;
		}
	}
	return $ip;
}
```

Now go to this section of the code near the top of the file

```
	<h3>".gettext('Host Status Detail')."</h3>
	<div class='detailWrapper'>
	<h4><em>".gettext('Host').": </em>{$dets['Host']}</h4>
	<h5><em>".gettext('Member of').": </em>{$dets['MemberOf']}</h5>
	<h5><a href='index.php?type=services&host_filter={$dets['Host']}' title='".gettext('See All Services For This Host')."'>".gettext('See All Services For This Host')."</a></h5>
	<div class='detailcontainer'>
	<fieldset class='hostdetails'>

```

and add the line to output the ip address.

```
	<h3>".gettext('Host Status Detail')."</h3>
	<div class='detailWrapper'>
	<h4><em>".gettext('Host').": </em>{$dets['Host']}</h4>
	<h5><em>IP Address: </em>".get_host_ip($dets['Host'])."</h5>
	<h5><em>".gettext('Member of').": </em>{$dets['MemberOf']}</h5>
	<h5><a href='index.php?type=services&host_filter={$dets['Host']}' title='".gettext('See All Services For This Host')."'>".gettext('See All Services For This Host')."</a></h5>
	<div class='detailcontainer'>
	<fieldset class='hostdetails'>

```

I expect this could be used almost anywhere you need the ip address, but this does it for me.

**Comment by mguthrie88** [comment]
Been a LONG time since I've been in this code, but I would consider looking to see if the address field is in the $dets array, and if it's not, push it into that. It's going to a lot quicker than looping through all of the hosts again just to pull out one field. The biggest challenges I ran into with VShell with with scaling problems in large environments. The goal is to only traverse the objects or status list one time and get what you need from it in a single run, otherwise those big loops will kill performance in a large environment.

**Comment by jahunter** [comment]
Yes that's a fair point.  I'll take a look at that as well then.

**Comment by jahunter** [comment]
I had another look at this and I wasn't keen on adding the host object information to the status details as this didn't seem right.  Nevertheless, I agree that looping through a large array would be cumbersome in a large environment.  Fortunately I seem to have had a bit of luck.

$data in 
`$data = $NagiosData->getProperty('hosts_objs');`
turns out to be an associative array, and after doing a dumparray I discovered that the keys are the host names.  So now my little function can go directly to the address without all that looping.  Here's the new function.

```
function get_host_ip($hostname){
	global $NagiosData;
	$data = $NagiosData->getProperty('hosts_objs');
	$hostobject = $data[$hostname];
	$ip = $hostobject['address'];
	if ($ip == NULL){
		$ip = "Not found";
	}
	return $ip;
}
```

**Comment by jahunter** [comment]
I've created a fork in GitHub with the new code and also created a pull request.

**Comment by EstebanMonge** [comment]
Is solved!

**Comment by EstebanMonge** [comment]
Thanks a lot!
